apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/memoliyasti/todowithflask/
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/k8s/

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  path: ./applications/todo
  sourceRef:
    kind: GitRepository
    name: todo-app
  targetNamespace: todo