apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/memoliyasti/react-article-display/
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/manifests/

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  path: ./applications/react
  sourceRef:
    kind: GitRepository
    name: react-app
  targetNamespace: app