apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/memoliyasti/todowithflask/
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/k8s/

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/memoliyasti/react-article-display/
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/manifests/

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: todo-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: todo-app
  targetNamespace: todo

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./deploy/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: react-app
  targetNamespace: app
